services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - ~\minio\data:/data
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: 14g9flbf
    ports:
      - "9000:9000"
      - "9001:9001"

  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - minio
      - postgres
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/db
      - MINIO_CLIENT_ENDPOINT=http://minio:9000
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=14g9flbf
      - MINIO_ACCESS_KEY=ROOTUSER
      - MINIO_SECRET_KEY=14g9flbf

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint:
      sh -c "mc alias set myminio http://minio:9000 ROOTUSER 14g9flbf && mc mb myminio/cloud-storage && mc policy set download myminio/cloud-storage"